# METADATA_FILE : 'Project_Data/Metadata.csv'
METADATA_FILE : 'Project_Data/Metadata_W_Product_detail.csv'
# EMBEDDING_FILE : 'Output/embeddings.pickle'
EMBEDDING_FILE : 'Output/embeddings_based_on_product_detail.pickle'
CATEGORY_DICT_PATH : 'Output/category_dict_.pickle'
ASIN_IND_MAPPING_DICT : 'Output/asin_mapping.pickle'
IMAGE_SIMILARITY_DICT : 'Output/Image_similar_items_dict.pickle'
IMAGE_IND : 'Output/Image_ind_v1.pickle'